#Turbo 20
Sub Main 
    | Set Resist to Cold, Poison, Magic, Fire
    | MR: 300 (120%) 	CR: 325 (130%) 	FR: 300 (120%)
    | PR: 200 (80%) 	DR: 600 (240%)
    /dgt ResistTypes cold|poison|magic|fire

    | Xiria (ST)
    /dt Xirael changeMT xirin
    /dt Xinshia changeMT xirin
    
    /dt Xirael autocureMTon 
    /dt Xinshia  autocureMTon

    | Xiris (MT) 
    /dt Xenshia autocureMTon
    /dt Tragic autocureMTon
/return
