#Turbo 20
Sub Main 
    | Set Aergia for looting
    /dt Aergia Looton ALL

    | Set the mode to efficient
    /dgt healMode EFFICIENT 

    | Set the offtanks
    /dt Xiria offtankON
    /dt Xirea offtankON
    /dt Xiris offtankON

    | Set auto curing the MT
    /dt Xanshia AutoCureMTOn

    | Set the aggro for Xirin
    /varset bln_tanking TRUE
    /varset bln_taunting TRUE
/return
