#EVENT JOB "#*#Who on Bertox#*#"

Sub Main
    :loop
    /doevents 
    /delay 10 
    /say Yo ho. No sun! 
     /doevents 
    /say A skeleton's day is never done.
     /doevents 
    /say Yo ho. No sun! 
     /doevents 
    /say A skeleton's day is never done.
    /delay 5 
    /goto :loop 
/return 

Sub EVENT_Job
    /doevents flush
    /tar abandoned
    /delay 5
    /say i am on the job
    /delay 40
    /keypress esc
/return 