#Turbo 20
#Event killMob "#*#KillMob #1# #*#"
Sub Main 
    | Set Xiris (MT) Healing 
    /dgt healMode EFFICIENT 
    /dgt changeHP 65
    /dgt UseFastOnly TRUE

    :loop 
        /doevents
        /delay 30
    /goto :loop
/return

Sub EVENT_active 
    /dgt healmode NORMAL
    /dgt changeHP 90
    /beep 
    /beep
    /doevents flush
/return

Sub EVENT_killMob
    /delay 10
    /dgga /attack on
/return