#define INI_CHAR        xiris_settings_character/BOT_${Me.Class.ShortName}_${Me.CleanName}.ini
#define INI_COMMON      xiris_settings_global/xiris_settings_common.ini
#include                xiris_includes/xiris_spell_routines.inc

#include                xiris_includes/xiris_buffing.inc
#include                xiris_includes/xiris_common.inc
#include                xiris_includes/xiris_curing.inc
#include                xiris_includes/xiris_dannet.inc
#include                xiris_includes/xiris_events.inc
#include                xiris_includes/xiris_clicks.inc

#Turbo 5

Sub Main 
    /mqclear
    /declare int_MTID       int     outer   ${Spawn[pc Xirin].ID}
    /declare bln_engaged    bool    outer   TRUE

    
    /declare str_currentSpellSet string outer default

    /declare arr_raidLeaders[9] string outer NULL

    | we might find this by looping through ${Raid.Member[${i}].GroupLeader} where i is 1-> ${Raid.Members} 
    | determining if if GroupLeader is true, and if so, add them to arr_raidLeaders
    /varset arr_raidLeaders[1] Xiris
    /varset arr_raidLeaders[2] Xiria
    /varset arr_raidLeaders[3] Xirea
    /varset arr_raidLeaders[4] Xirin
    /varset arr_raidLeaders[5] Xeqisa
    /varset arr_raidLeaders[6] Xaeliea
    /varset arr_raidLeaders[7] Xaexa
    /varset arr_raidLeaders[8] Xaia
    /varset arr_raidLeaders[9] Xepatia

    /call xbot_initialize_dannet
	/call xbot_initialize_spellRoutines
    /call xbot_initialize_events
	/call xbot_initialize_buffing
	/call xbot_initialize_burning
    /call xbot_initialize_curing
    /call xbot_initialize_clicking
   

    :MainLoop
        
		/if (${Me.Hovering} || ${Window[tradewnd].Open} || ${Window[lootwnd].Open}) /goto :MainLoop


        | Debug check the burning events
        /call Events_Burning
        /call Events_Clicking

        /if (${bln_engaged}) {

            
        } else {

            |/if (!${timer_check_utilities}) /call chkUtils
			|/if (!${timer_check_loot} && ${bln_looting}) /call chkLoot

        }
        /delay 20
        /end
        /goto :MainLoop
/return 
