
#turbo 120
#define INI_zoneInfo xiris_common/xiris_pull_zoneinfo.ini

Sub Main
    /mqclear
/declare int_maxPullCount int outer 3
    /call SetAlerts

  
/return

Sub SetAlerts
    /echo \aoSetAlerts \aw---------------
	/declare i		int		local 0
	/declare test	string 	local NULL
	/declare sz  	string 	local ${Zone.ShortName}

	| handle the OOW instances
	/if (${sz.Find[dranikcatacombs]}) {
		/varset sz dranikcatacombs
	} else /if (${sz.Find[dranikhollows]}) {
		/varset sz dranikhollows
	} else /if (${sz.Find[draniksewers]}) {
		/varset sz draniksewers
	}

    | handle setting maxpull from INI
    /varset int_maxPullCount ${Ini[INI_zoneInfo,${sz},MAXPULL,3]}

	| set the entry count
	/declare avoidCount  ${Ini.File[INI_zoneInfo].Section[${sz}].Key[AVOID].Count}
	/declare huntCount  ${Ini.File[INI_zoneInfo].Section[${sz}].Key[HUNT].Count}
    /echo \aoAvoidCount:\ag${avoidCount} \aoHuntCount:\ag${huntCount} \aoMaxPullCount:\ag${int_maxPullCount}

    | set the avoidance list
    /alert clear 1
    /if (${avoidCount}) {  
        /for i 1 to ${avoidCount}
            /varset test ${Ini.File[INI_zoneInfo].Section[${sz}].Key[AVOID].ValueAtIndex[${i}]}
            /alert add 1 ${test}
        /next i
    }

    | set the hunter list
    /alert clear 2
	/if (${huntCount}) {
        /for i 1 to ${huntCount}
		/varset test ${Ini.File[INI_zoneInfo].Section[${sz}].Key[HUNT].ValueAtIndex[${i}]}
		/alert add 2 ${test}
	    /next i
    }
/return
