
#Turbo 10
#include xiris_common/xiris_common.inc

#Event brewval "Brewing:#1##2#"
#Event brewcheck "#*#brewcheck#*#"

#EVENT HanvarChainsOn		"#*#entangles you in chains#*#"
#EVENT HanvarChainsOff		"#*#You break free of the chains#*#"

Sub Main
	|/call xbot_initialize ${_tank1Name} ${_tank2Name} ${_tank3Name} ${_healPoint} ${_assistArgs}
	/call xbot_initialize_spellRoutines
	/call xbot_initialize_burns
	/delay 20
	/echo \ar ${BURN_9}
	/call MQ2Cast "Raging Taelosian Alloy Axe" item 2s

/return
