#Turbo 20
Sub Main 
    | Set Xiria (OT) Healing
    /dt Theist changeMT Xiria
    /dt Tragic changeMT Xiria
    /dt Xirael changeMT Xiria
    /dt Xinshia changeMT Xiria
    /dt Xenshia changeMT xiria

    | Set the mode to efficient
    /dgt healMode EFFICIENT 
    /dex xiria /mac stand 
    /dex xiria /varset bln_tanking TRUE
    /varset bln_tanking TRUE
    /mac stand

/return
