-- DROP TABLE IF EXISTS Characters;
-- CREATE TABLE IF NOT EXISTS Characters(
-- ID INTEGER PRIMARY KEY AUTOINCREMENT,
-- Name TEXT UNIQUE,
-- SpawnID INTEGER UNIQUE,
-- ZoneID INTEGER NOT NULL
-- );
-- 

--INSERT OR IGNORE INTO Characters (Name,SpawnID,ZoneID) VALUES ('Xiria',402,345) ;
--SELECT * FROM Characters ORDER BY Id;

-- DROP TABLE IF EXISTS MarkOfDeath;
-- CREATE TABLE IF NOT EXISTS MarkOfDeath(
-- ID INTEGER PRIMARY KEY AUTOINCREMENT,
-- Name TEXT UNIQUE,
-- SpawnID INTEGER UNIQUE,
-- Counters TINYINT NOT NULL,
-- CureInProcess BOOL NOT NULL DEFAULT FALSE);
-- 
--INSERT OR IGNORE INTO MarkOfDeath(SpawnID,Counters) VALUES (402,19);
--INSERT OR REPLACE INTO MarkOfDeath(Name,SpawnID,Counters,CureInProcess) VALUES ('Xiris', 22, 14,FALSE);
SELECT * FROM MarkOfDeath;
SELECT * FROM observers;