|**
----------------------------
CHARM CASTING HANDLERS
----------------------------
This includes the charm setup (see xiris_charm.ini) which has mobs to force 
charm on check (ie: Specialization mote of frost, OMM lieutenants, etc)
______________________________________________
REVISION HISTORY
    06.24.22    xiris	INITIAL REVISION
**|



#EVENT  CharmON "#*#CharmON#*#"
#EVENT  CharmNPC "#*#CharmNPC #1#"